export const workoutTypes = [
  "Push",
  "Pull",
  "Legs",
  "Shoulders",
  "Arms",
  "Upperbody",
] as const;

export const exercisesByType = {
  Push: [
    "Bench Press",
    "Push-Ups",
    "Dumbbell Press",
    "Military Press",
    "Incline Bench Press",
    "Incline Dumbbell Press",
    "Dips",
    "Chest Flyes",
    "Tricep Pushdowns",
    "Skull Crushers",
    "Overhead Press",
    "Arnold Press",
    "Close Grip Bench Press",
    "Tricep Extensions",
    "Front Raises",
    "Decline Push-Ups",
    "Pec Deck Machine",
  ],
  Pull: [
    "Pull-Ups",
    "Deadlifts",
    "Seated Rows",
    "Chin-Ups",
    "Lat Pulldowns",
    "Straight Arm Pulldown",
    "Face Pulls",
    "Bent Over Rows",
    "Barbell Curls",
    "Hammer Curls",
    "Inverted Rows",
    "Reverse Flyes",
    "T-Bar Rows",
    "Shrugs",
    "Underhand Grip Pulldowns",
    "Single Arm Rows",
  ],
  Legs: [
    "Squats",
    "Lunges",
    "Deadlifts",
    "Leg Press",
    "Calf Raises",
    "Hamstring Curls",
    "Leg Extensions",
    "Romanian Deadlifts",
    "Hack Squats",
    "Step-Ups",
    "Bulgarian Split Squats",
    "Sumo Deadlifts",
    "Box Jumps",
    "Walking Lunges",
  ],
  Shoulders: [
    "Shoulder Press",
    "Lateral Raises",
    "Front Raises",
    "Reverse Flyes",
    "Shrugs",
    "Upright Rows",
    "Arnold Press",
    "Lateral Dumbbell Raises",
    "Face Pulls",
    "Barbell Shrugs",
    "Seated Dumbbell Press",
    "Military Press",
    "Dumbbell Shrugs",
    "Clean and Press",
    "Plate Raises",
  ],
  Arms: [
    "Bicep Curls",
    "Tricep Dips",
    "Hammer Curls",
    "Skull Crushers",
    "Preacher Curls",
    "Concentration Curls",
    "Tricep Kickbacks",
    "Barbell Curls",
    "EZ-Bar Curls",
    "Close Grip Bench Press",
    "Spider Curls",
    "Overhead Tricep Extensions",
    "Zottman Curls",
    "Reverse Curls",
    "French Press",
  ],
  Upperbody: [
    "Bench Press",
    "Pull-Ups",
    "Rows",
    "Push-Ups",
    "Shoulder Press",
    "Dips",
    "Deadlifts",
    "Chest Flyes",
    "Lat Pulldowns",
    "Bent Over Rows",
    "Incline Bench Press",
    "Tricep Pushdowns",
    "Military Press",
    "Barbell Curls",
    "Face Pulls",
  ],
};
